views:
  - title: Home
    icon: mdi:home-variant
    path: home
    type: custom:glace-layout
    cards:
      - type: custom:glace-homepage-card
        mode: home
  - title: Lighting
    icon: mdi:lightbulb-group-outline
    path: lighting
    type: custom:glace-layout
    cards:
      - type: custom:glace-homepage-card
        mode: lighting
  - title: Switches
    icon: mdi:toggle-switch-outline
    path: switches
    type: custom:glace-layout
    cards:
      - type: custom:glace-homepage-card
        mode: switches
